name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v3
      - name: Download github-contrib-stats
        run: |
          curl -sSL --output /tmp/github-contrib-stats.tar.gz https://github.com/j178/github-contrib-stats/releases/latest/download/github-contrib-stats-x86_64-unknown-linux-gnu.tar.gz && \
          tar -xf /tmp/github-contrib-stats.tar.gz -C /tmp --strip-components=1 && \
          chmod +x /tmp/github-contrib-stats
      - name: Update stats
        run: /tmp/github-contrib-stats -u ${{ github.repository_owner }} -o README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
            if git diff --quiet; then
              echo "nothing new"
              exit 0
            fi
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m "Update README"
            git push
