name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v4
      - name: Download github-contrib-stats
        uses: robinraju/release-downloader@v1.8
        with:
          repository: j178/github-contrib-stats
          latest: true
          fileName: "github-contrib-stats*.tar.gz"
          extract: true
      - name: Update stats
        run: ./github-contrib-stats -u ${{ github.repository_owner }} -o README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add README.md
            git commit -m "Update README"
            git push
